-- Insertar datos ficticios adicionales
INSERT INTO games (title, descripcion, genre, console, generation, release_year, precio, cover)
VALUES
    ('Street Fighter Alpha 3', 'Engage in fierce one-on-one battles in Street Fighter Alpha 3. Choose from a roster of iconic fighters, each with unique abilities and special moves. With fast-paced gameplay and stunning visuals, this classic fighting game delivers an arcade experience like no other.', 'Fighting', 'PlayStation 1', 5, 1999, 14.99, 'https://cdn.mobygames.com/covers/91439-street-fighter-alpha-3-playstation-front-cover.jpg'),
    ('Spyro the Dragon', 'Embark on a colorful and whimsical adventure as Spyro the Dragon. Explore expansive worlds, solve puzzles, and collect gems in this beloved platformer. With charming characters and engaging gameplay, Spyro the Dragon capt-ivates players of all ages.', 'Platformer', 'PlayStation 1', 5, 1998, 19.99, 'https://cdn.mobygames.com/covers/4799551-spyro-the-dragon-playstation-front-cover.jpg'),
    ('Tomb Raider', 'Uncover the mysteries of ancient tombs in the original Tomb Raider. As the iconic adventurer Lara Croft, you navigate treacherous environments, solve puzzles, and face formidable enemies. With groundbreaking 3D graphics, Tomb Raider set the standard for action-adventure gaming.', 'Action-Adventure', 'PlayStation 1', 5, 1996, 9.99, 'https://cdn.mobygames.com/covers/4046877-tomb-raider-playstation-front-cover.jpg'),
    ('Resident Evil 2', 'Experience the horror of Raccoon City in Resident Evil 2. Navigate through a zombie-infested city as Leon Kennedy or Claire Redfield, each with their own unique story. With atmospheric tension and gripping storytelling, Resident Evil 2 remains a landmark in survival horror.', 'Survival Horror', 'PlayStation 1', 5, 1998, 24.99, 'https://cdn.mobygames.com/covers/4717771-resident-evil-2-playstation-front-cover.jpg'),
    ('Metal Gear Solid', 'Step into the world of tactical espionage in Metal Gear Solid. As Solid Snake, you infiltrate a nuclear weapons facility to neutralize a terrorist threat. With cinematic storytelling, complex characters, and innovative gameplay mechanics, Metal Gear Solid redefined the stealth genre.', 'Stealth', 'PlayStation 1', 5, 1998, 29.99, 'https://cdn.mobygames.com/covers/8618053-metal-gear-solid-playstation-front-cover.jpg'),
    ('Max Payne 3', 'Immerse yourself in the gritty world of Max Payne 3. As a troubled ex-cop, navigate through a story of betrayal and redemption. With intense gunplay, cinematic storytelling, and a noir atmosphere, Max Payne 3 delivers a gripping third-person shooter experience.', 'Third-Person Shooter', 'PlayStation 3', 7, 2012, 29.99, 'https://cdn.mobygames.com/covers/6693853-max-payne-3-playstation-3-front-cover.jpg'),
    ('Dark Souls', 'Embark on a challenging and atmospheric journey in Dark Souls. Face brutal enemies and overcome intricate level designs in this action RPG. With deep lore, punishing difficulty, and rewarding gameplay, Dark Souls has become a landmark title for hardcore gamers.', 'Action RPG', 'PlayStation 3', 7, 2011, 19.99, 'https://cdn.mobygames.com/covers/6987557-dark-souls-playstation-3-front-cover.jpg'),
    ('Grand Theft Auto V', 'Explore the vast open-world of Los Santos in Grand Theft Auto V. Play as three distinct protagonists and engage in heists, missions, and mayhem. With stunning visuals, a dynamic narrative, and a living, breathing game world, GTA V sets a new standard for open-world games.', 'Action-Adventure', 'PlayStation 3', 7, 2013, 39.99, 'https://cdn.mobygames.com/covers/6090098-grand-theft-auto-v-playstation-3-front-cover.jpg'),
    ('God Of War III', 'Continue the epic saga of Kratos in God Of War III. With upgraded visuals and epic set pieces, Kratos ascends Mount Olympus to confront the gods. With intense combat, breathtaking scale, and a powerful narrative, God Of War III is a masterpiece of action gaming.', 'Action-Adventure', 'PlayStation 3', 7, 2010, 34.99, 'https://cdn.mobygames.com/covers/5875653-god-of-war-iii-playstation-3-front-cover.jpg'),
    ('Battlefield 4', 'Engage in intense modern warfare in Battlefield 4. With a dynamic multiplayer experience and a gripping single-player campaign, Battlefield 4 showcases the chaos of large-scale battles. Utilize vehicles, teamwork, and strategy to emerge victorious on the battlefield.', 'First-Person Shooter', 'PlayStation 3', 7, 2013, 24.99, 'https://cdn.mobygames.com/covers/6731533-battlefield-4-playstation-3-front-cover.jpg'),
    ('God Of War (2018)', 'Experience the reimagined journey of Kratos and Atreus in God of War (2018). This action-adventure masterpiece takes you through the realms of Norse mythology, featuring epic battles, a gripping narrative, and stunning visuals. With a powerful father-son dynamic, God of War (2018) sets a new standard for storytelling in gaming.', 'Action-Adventure', 'PlayStation 4', 8, 2018, 49.99, 'https://cdn.mobygames.com/covers/8019897-god-of-war-playstation-4-front-cover.jpg'),
    ('Red Dead Redemption II', 'Immerse yourself in the vast landscapes of the American Wild West in Red Dead Redemption II. As Arthur Morgan, navigate the challenges of the Van der Linde gang and experience a narrative-rich open-world adventure. With stunning realism, deep character development, and a dynamic ecosystem, RDR2 is a true western epic.', 'Action-Adventure', 'PlayStation 4', 8, 2018, 59.99, 'https://cdn.mobygames.com/covers/7422709-red-dead-redemption-ii-playstation-4-front-cover.jpg'),
    ('Bloodborne', 'Descend into the nightmarish world of Yharnam in Bloodborne. This action RPG challenges players with fast-paced combat, eldritch horrors, and intricate level design. With its gothic atmosphere and relentless difficulty, Bloodborne captivates players seeking a dark and challenging gaming experience.', 'Action RPG', 'PlayStation 4', 8, 2015, 39.99, 'https://cdn.mobygames.com/covers/11078336-bloodborne-playstation-4-front-cover.jpg'),
    ('Sekiro', 'Master the way of the shinobi in Sekiro: Shadows Die Twice. From the developers of Dark Souls and Bloodborne, Sekiro offers intense swordplay, stealth, and a captivating feudal Japan setting. With precision combat and a focus on mastery, Sekiro provides a unique and challenging experience for players.', 'Action-Adventure', 'PlayStation 4', 8, 2019, 54.99, 'https://cdn.mobygames.com/covers/7868291-sekiro-shadows-die-twice-playstation-4-front-cover.jpg'),
    ('Doom Eternal', 'Unleash hell on Earth in Doom Eternal. This fast-paced first-person shooter puts players in the boots of the Doom Slayer as they face hordes of demons. With relentless action, dynamic weapons, and visceral combat, Doom Eternal continues the legacy of the iconic Doom series.', 'First-Person Shooter', 'PlayStation 4', 8, 2020, 44.99, 'https://cdn.mobygames.com/covers/8654561-doom-eternal-playstation-4-front-cover.jpg'),
    ('Black', 'Embark on an adrenaline-fueled journey through the shadows of covert operations in Black. As an elite operative, you navigate through intense urban environments, engaging in high-stakes gunfights and explosive scenarios. With cutting-edge graphics and a gripping narrative, Black delivers an immersive experience that blurs the line between chaos and precision.', 'First-Person Shooter', 'PlayStation 2', 6, 2006, 19.99, 'https://cdn.mobygames.com/covers/4359409-black-playstation-2-front-cover.jpg'),
    ('Grand Theft Auto: San Andreas', 'Explore the sprawling landscapes of San Andreas, a fictional state teeming with criminal opportunities. In Grand Theft Auto: San Andreas, you step into the shoes of Carl Johnson as he returns to his hometown to confront corruption, betrayal, and chaos. This open-world masterpiece allows players to engage in a gripping narrative, diverse missions, and an expansive range of criminal activities.', 'Action-Adventure', 'PlayStation 2', 6, 2004, 29.99, 'https://cdn.mobygames.com/covers/4554918-grand-theft-auto-san-andreas-playstation-2-front-cover.jpg'),
    ('God Of War II', 'Ascend the heights of Mount Olympus once again as Kratos, the God of War, in this epic sequel. God Of War II thrusts players into a world of Greek mythology, combining intense combat, intricate puzzles, and a gripping storyline. With improved graphics and an evolved combat system, Kratos seeks revenge against the gods in a quest that challenges both his strength and his humanity.', 'Action-Adventure', 'PlayStation 2', 6, 2007, 39.99, 'https://cdn.mobygames.com/covers/5088103-god-of-war-ii-playstation-2-front-cover.jpg'),
    ('Resident Evil 4', 'Witness the evolution of survival horror in Resident Evil 4, where Leon S. Kennedy faces a new breed of terror in a remote European village. Unravel the mystery behind a sinister cult and rescue the Presidents daughter from a horde of mutated beings. With a dynamic over-the-shoulder perspective, strategic combat, and atmospheric tension, Resident Evil 4 redefines the horror gaming experience.', 'Survival Horror', 'PlayStation 2', 6, 2005, 24.99, 'https://cdn.mobygames.com/covers/4480917-resident-evil-4-playstation-2-front-cover.jpg'),
    ('Shadow of the Colossus', 'Embark on a hauntingly beautiful quest in Shadow of the Colossus, a unique blend of action and exploration. As Wander, you traverse a desolate landscape on horseback, seeking to resurrect a loved one. The games innovative approach features colossal, majestic creatures as the only adversaries, each requiring careful strategy and skillful climbing. Shadow of the Colossus captivates with its emotional narrative and breathtaking environments.', 'Action-Adventure', 'PlayStation 2', 6, 2005, 34.99, 'https://cdn.mobygames.com/covers/4317156-shadow-of-the-colossus-playstation-2-front-cover.jpg');






