### Recuperar todos los elementos
GET http://localhost:3000

### Recuperar todas las consolas
GET http://localhost:3000/consoles

### Recuperar todas las generaciones
GET http://localhost:3000/generations

### Recuperar elemento por id
GET http://localhost:3000/id/36

### Recuperar juegos por consola
GET http://localhost:3000/console/ps1

### Recuperar juegos por generación
GET http://localhost:3000/generation/1

